name: wake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/45 * * * *" #   分 时 日 月 周

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: wake sanbo
        shell: bash
        continue-on-error: true
        run: |
          echo "----duck2api----"
          curl --location 'https://sanbo1200-duck2api.hf.space/hf/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----d1----"
          curl --location 'https://sanbo1200-d1.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----d2----"
          curl --location 'https://sanbo1200-d2.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----d3----"
          curl --location 'https://sanbo1200-d3.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----d4----"
          curl --location 'https://sanbo1200-d4.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----d5----"
          curl --location 'https://sanbo1200-d5.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----ddg----"
          curl --location 'https://sanbo1200-ddghat.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----sanbo110----"
          curl --location 'https://sanbo110-test.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----whats----"
          curl --location 'https://sanbo110-whats-this.hf.space/api/v1/chat/completions' \
          --hea¡der 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "----gpt-4o----"
          curl 'https://sanbo1200-gpt4free.hf.space/backend-api/v2/conversation' -H 'accept: text/event-stream' -H 'content-type: application/json' -H 'origin: https://sanbo1200-gpt4free.hf.space' --data-raw '{"id":"7450489680389462209","conversation_id":"49de3eec-3cd5-443d-b598-193e44fda35","model":"gpt-4o","web_search":true,"provider":"","messages":[{"role":"user","content":"阿拉伯数字的由来"}],"auto_continue":true,"download_images":true,"api_key":null,"ignored":[]}'
          echo "-------flux-------"
          curl 'https://sanbo1200-gpt4free.hf.space/backend-api/v2/conversation' -H 'accept: text/event-stream' -H 'content-type: application/json' --data-raw '{"id":"7450491277595787166","conversation_id":"49de3eec-3cd5-443d-b598-193e44fda35","model":"flux","web_search":true,"provider":"","messages":[{"role":"user","content":"一只可爱的猫"},{"role":"user","content":"a cute cat"}],"auto_continue":true,"download_images":true,"api_key":null,"ignored":[]}'

      - name: wake g4f
        shell: bash
        continue-on-error: true
        run: |
          echo "----g4f----"
          curl https://sanbo1200-gpt4free.hf.space/v1/models

      - name: wake apin
        shell: bash
        continue-on-error: true
        run: |
          echo "gpt-4o-mini ----你是谁，你的知识库更新到什么时间-"
          curl --location 'https://sanbo1200-apin.hf.space/completions' \
          --header 'Content-Type: application/json' \
          --data '{
              "messages": [{"role":"system","content":"你是一个辅助机器人，特点贼聪明"},{"role": "user", "content": "你是谁，你的知识库更新到什么时间"}],
              "stream": false
              }'


      - name: wake ethan
        shell: bash
        continue-on-error: true
        run: |
          echo "-----dai----"
          curl --location 'https://ethanmaht-dai.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "-----dg-gtp-4o-mini-0----"
          curl --location 'https://ethanmaht-dg-gtp-4o-mini-0.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          echo "-----dg-gpt4o-mini-1----"
          curl --location 'https://ethanmaht-dg-gpt4o-mini-1.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'

      - name: wake yxmnjxzx
        shell: bash
        continue-on-error: true
        run: |
          echo "----# https://huggingface.co/spaces/yxmnjxzx/openai-reverse-proxy"
          curl --location 'https://yxmnjxzx-openai-reverse-proxy.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o",
               "messages": [
                  {
                    "role": "system",
                    "content": "You are a helpful assistant."
                  },
                  {
                    "role": "user",
                    "content": "Hello, who are you?"
                  }
                ],
               "stream": false,
                "temperature": 0.7,
                "max_tokens": 8000
             }'
