name: wake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/45 * * * *" #   分 时 日 月 周

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: wake duck2api
        shell: bash
        continue-on-error: true
        run: |
          curl --location 'https://sanbo1200-duck2api.hf.space/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'

      - name: wake d1
        shell: bash
        continue-on-error: true
        run: |
          curl --location 'https://sanbo1200-d1.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'


      - name: wake d2
        shell: bash
        continue-on-error: true
        run: |
          curl --location 'https://sanbo1200-d2.hf.space/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          curl --location 'https://sanbo1200-d2.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'


      - name: wake d3
        shell: bash
        continue-on-error: true
        run: |
          curl --location 'https://sanbo1200-d3.hf.space/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'
          curl --location 'https://sanbo1200-d3.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'


      - name: wake ddghat
        shell: bash
        continue-on-error: true
        run: |
          curl https://sanbo1200-ddghat.hf.space/models

          curl --location --request POST 'https://sanbo1200-ddghat.hf.space/completions' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "model": "gpt-4o-mini",
                "messages": [
                    {
                        "role": "user",
                        "content": "你是什么模型?你的知识库截止到什么时间?"
                    }
                ],
                "stream": false
            }'



      - name: wake apin
        shell: bash
        continue-on-error: true
        run: |
          curl --location 'https://sanbo1200-apin.hf.space/completions' \
          --header 'Content-Type: application/json' \
          --data '{
              "messages": [{"role": "user", "content": "你是谁，你知道西红柿炒鸡蛋怎么做吗"}],
              "stream": false
              }'


      - name: wake dai
        shell: bash
        continue-on-error: true
        run: |
          curl --location 'https://ethanmaht-dai.hf.space/api/v1/chat/completions' \
          --header 'Content-Type: application/json' \
          --data '{
               "model": "gpt-4o-mini",
               "messages": [{"role":"system","content":"你是一个辅助机器人"},{"role": "user", "content": "你的知识库最后什么日期"}],
               "stream": false
             }'



